language: node_js
node_js:
   - "0.10"

cache:
  directories:
    - frontEnd/node_modules
    - frontEnd/bower_components
    - test/node_modules

install:
  - ./run.sh install

script:
  - ./run.sh start
  - ./run.sh test
  - ./run.sh stop
  - cat ./frontEnd/log/appOutFile.log
  - cat ./frontEnd/log/appErrFile.log