language: node_js
node_js:
   - "0.10"

cache:
  directories:
    - frontEnd/node_modules
    - frontEnd/bower_components
    - test/node_modules

install:
  - ./run.sh install

script:
  - ./run.sh test