language: node_js
node_js:
   - "0.10"

cache:
  directories:
    - frontEnd/node_modules
    - frontEnd/bower_components
    - test/node_modules

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - ./run.sh install

script:
  - ./run.sh start
  - ./run.sh test
  - ./run.sh stop
  - ./run.sh show-logs