language: node_js
node_js:
   - "0.10"

cache:
  directories:
    - frontEnd/node_modules
    - frontEnd/bower_components
    - test/node_modules

before_install:
  - sudo apt-get install -y libssl0.9.8
  - sudo wget http://packages.couchbase.com/releases/2.5.1/couchbase-server-enterprise_2.5.1_x86_64.deb
  - sudo dpkg -i couchbase-server-enterprise_2.5.1_x86_64.deb
  - sudo service couchbase-server start
  - /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username=Administrator --cluster-init-password=password --cluster-init-ramsize=256
  - /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=hemlock --bucket-password=password --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=100 --bucket-replica=0 -u Administrator -p password

install:
  - ./run.sh install

script:
  - ./run.sh start
  - ./run.sh test
  - ./run.sh stop
  - ./run.sh show-logs